fix deprecation warning and import reverse from django.urls
purelabs/django-bulk-admin pull request #11
Opened 2019-01-13 21:25 UTC by wayne530

2019-01-15 14:04 UTC, sebslomski requested changes

2019-01-15 14:04 UTC, sebslomski commented on .gitignore
> +.idea/
Please remove this one.

2019-01-15 16:15 UTC, wayne530 commented on .gitignore
> +.idea/
done in eed316a

2019-01-15 18:08 UTC, sebslomski approved these changes

2019-01-18 15:47 UTC, wayne530 commented
@sebslomski Any change on getting this merged in?

2020-09-17 04:49 UTC, closed without merging